import JSZip from 'jszip';

export async function downloadSourceCodeZip(): Promise<void> {
  const zip = new JSZip();

  // Create README entry inside zip
  zip.file(
    'README.md',
    `# HydroPulse - Smart Hydration Source Code Archive
Generated by HydroPulse Web Platform.
Tech Stack: React 19, TypeScript, Vite, Tailwind CSS v4.
`
  );

  const blob = await zip.generateAsync({ type: 'blob' });
  const downloadUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = downloadUrl;
  link.download = `hydropulse-source-code-${Date.now()}.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(downloadUrl);
}
